# Generated by Django 5.1 on 2024-09-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=100, verbose_name='Описание задачи')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.IntegerField(choices=[(1, 'completed'), (0, 'not completed')], default=1, max_length=1)),
            ],
        ),
    ]
