# Generated by Django 5.1 on 2024-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='task',
            field=models.ManyToManyField(to='tasks.task'),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
