# Generated by Django 5.1 on 2024-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tags_task_remove_tags_tag_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='tasks.tags'),
        ),
    ]
