# Generated by Django 5.1 on 2024-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'high priority'), ('M', 'middle priority'), ('L', 'low priority')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
