# Generated by Django 5.1 on 2024-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_priority_alter_tags_slug_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'high priority'), (2, 'middle priority'), (1, 'low priority')], default=None, null=True),
        ),
    ]
