# Generated by Django 5.1 on 2024-09-15 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='tasks_for_allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
