# Generated by Django 5.1.1 on 2024-09-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basket_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
